### ISSUE TITLE
axisY title getting cut off on left edge

### ISSUE THREAD

**Issue by wedgef5** [alexstanbury/chartist-plugin-axistitle#1]
I'm having an issue, which is also evident in the example on the Chartist plugins page, where the left edge of the y-axis title is cut off.

How do I go about fixing this?

**Comment by wedgef5** [comment]
Forgot to attach my code...

``` javascript
    chart = new Chartist.Line('.ct-chart', data, {
        lineSmooth: Chartist.Interpolation.simple(),
        low: 0,
        fullWidth: true,
        chartPadding: {
            right: 30,
            left: 30,
            bottom: 30
        },
        plugins: [
            Chartist.plugins.ctAxisTitle({
                axisX: {
                    axisTitle: 'Date/Time',
                    axisClass: 'ct-axis-title',
                    offset: {
                        x: 0,
                        y: 50
                    },
                    textAnchor: 'middle'
                },
                axisY: {
                    axisTitle: 'Seconds',
                    axisClass: 'ct-axis-title',
                    offset: {
                      x: 0,
                      y: 0
                    },
                    textAnchor: 'middle'
                }
            })
        ]
    });
```

Also, I have tried varying amounts of left padding, but it never seems to help.

**Comment by astanb** [comment]
Hi, thanks for reporting this. If you change axisY.offset.y to be -5, it will then show the whole of the title. When I get a chance I will remove the need for this as it should be displaying properly by default.

The reason you change the y value is because the title's axis gets rotated by 90 degrees, therefore swapping over the axes compared to how you would normally position using x and y. I will either make this clear in the docs or look at another approach.

**Comment by wedgef5** [comment]
Sweet.  That fixed it.  Thanks for the quick reply and putting this plugin out there.  You saved me a ton of time trying to draw it manually myself.

**Comment by astanb** [comment]
You're welcome, thanks for using it! :]
